.TH DISPLAY-KIOSK 1 16/08/2013 0.2.0 "Display Kiosk Manual"

.SH NAME
display-kiosk \- Display a website in a stripped down kiosk

.SH SYNOPSIS
\fIdisplay-kiosk\fR <url>
        [\-\-hide\-cursor]
        [\-\-hide\-status] [\-\-hide-toolbar]
        [\-\-prevent\-close] [\-\-prevent\-upload]
        [\-\-auto\-scroll
            [\-\-auto\-scroll\-delta <pixels>]
            [\-\-auto\-scroll\-interval <milliseconds>] ]
        [\-\-auto\-reload <seconds>]
        [\-\-window]

.SH HIDING CHROME
.sp
By default the cursor, a status bar and a toolbar will be displayed.

.PP
\-\-hide\-cursor
.RS 4
Hide the cursor.
.RE

.PP
\-\-hide\-status
.RS 4
Hide the status bar.
.RE

.PP
\-\-hide\-toolbar
.RS 4
Hide the toolbar.
.RE

.SH LOCK DOWN FEATURES

.PP
\-\-prevent\-close
.RS 4
Ignore window close events. A window manager might still provide ways to
minimize the window, switch the window or kill a process, so you might need
to configure that, too, if you are using one.
.RE

.PP
\-\-prevent\-upload
.RS 4
Do not allow uploading files from the display kiosk.
.RE

.SH AUTO SCROLLING

.PP
\-\-auto\-scroll
.RS 4
Enable auto scrolling.
.RE

Once enabled you may configure auto scrolling more finely.

.PP
\-\-auto\-scroll\-delta <pixels>
.RS 4
The number of pixels to scroll at a time. Defaults to 300.
.RE

.PP
\-\-auto\-scroll\-interval <milliseconds>
.RS 4
The number of milliseconds to wait between scrolling steps. Defaults to 5000.
.RE

.SH AUTO RELOADING

.PP
\-\-auto\-reload <seconds>
.RS 4
Automatically reload after the given number of seconds. Will only reload if
mouse and keyboard are idle. If auto scrolling is enabled, reloading will be
deferred until scrolling reaches the end.

When reloading, session cookies will be cleared, so you can use this on an
interactive kiosk to automatically logout after a while.

.SH OTHER OPTIONS

.PP
\-\-window
.RS 4
Do not open fullscreen. Use for testing.
.RE

.PP
\-\-reset-text <reset-text>
.RS 4
The label of the reset button on the toolbar. Defaults to "Reset".
.RE

.SH COPYRIGHT
Copyright (c) 2013 Niklas Fiekas <niklas.fiekas@tu-clausthal.de>
.sp
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
.sp
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU General Public License for more details.
.sp
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
.sp
On Debian systems, the complete text of the GNU General Public
License version 3 can be found in \fI/usr/share/common-licenses/GPL-3\fR.
